# This file is part of SMARTIES.
# Copyright (c) 2024-2026 bers of the Simons Simons Observatory Collaboration.
# lease refer to the LICENSE file in the root of this repository.


import os
import yaml
import numpy as np
import healpy as hp
from opt_einsum import contract
import h5py
from pixell import enmap
from smarties.hn import Spin_maps, Spin_nm
from smarties.tools import flatten_CAR_maps, reweight_h_maps

__all__ = [
    'build_mask_from_toast_h_maps',
    'read_file',
    'read_toast_h_maps',
    'read_lbs_h_maps',
    'read_spherical_derivatives_from_file',
    'read_values_from_yaml_file',
]

def read_file(
        name_file:str, 
        format_file:str='fits', 
        boolean_mask:np.ndarray=None,
        reorder: bool=False,
        dtype=np.float64,
        projection_pixel: str='healpix'
    ):
    """
    Read the $h_n$ maps as provided either in FITS, NPY or NPZ
    format, and eventually mask them. 

    Parameters
    ----------
    name_file: str
        Path to the $h_n$ file to be read. If the path provided does
        not contain the fomat suffix, in '.fits', '.npy' or '.npz',
        the suffix corresponding to the format indicated in format_file
        will be concatenated. 
    format_file: str
        String indicated the format of the file to be read, must be 
        either 'fits', 'npy' or 'npz' otherwise a ValueError is raised 
    boolean_mask: array[bool] | Ellipsis
        Optional, boolean array corresponding to the selected pixels in 
        the array to retain after loading the file. By default, return 
        all pixels. Note that this option is not active for 'npz' format
        files. If None, the full maps are read.

    Returns
    -------
        Array containing the $h_n$ map read, from which only the relevant
        pixels are possibly retained. 
    """
    if boolean_mask is None:
        boolean_mask = ...

    if format_file == 'fits':
        if not name_file.endswith('.fits'):
            name_file = name_file + '.fits'
        if projection_pixel == 'healpix':
            return hp.read_map(name_file)[boolean_mask]
        else:
            return flatten_CAR_maps(enmap.read_map(name_file))[boolean_mask]
    elif format_file == 'npy':
        if not name_file.endswith('.npy'):
            name_file = name_file + '.npy'
        # return np.load(name_file)[boolean_mask]
        return np.memmap(name_file, mode='r', dtype=dtype)[boolean_mask]
    elif format_file == 'npz':
        if not name_file.endswith('.npz'):
            name_file = name_file + '.npz'
        return np.load(name_file) #, allow_pickle=True)
    elif format_file in ['h5', 'hdf5', 'H5', 'hdf']:
        if not name_file.endswith(format_file):
            name_file = name_file + '.' + format_file
        if projection_pixel == 'healpix':
            return h5py.File(name_file, "r")
        else:
            return flatten_CAR_maps(enmap.read_map(name_file))[boolean_mask]
    else:
        raise ValueError("Unknown format: {}".format(format_file))


def read_toast_h_maps(
        list_name_files: list[str], 
        list_spin: list[int]=[2,4], 
        list_prefix: list[str]=['A_', 'B_'], 
        list_weights=None, 
        mask: np.ndarray=None, 
        format_file: str='npz',
        new_weighting_bool: bool=False,
        single_precision: bool=False,
        duplicate_maps_with_prefix=False,
        projection_pixel: str='healpix',
    ):
    """
    Read the $h_n$ map as generated by TOAST, 
    which filename is preferrentially given as
        filever_w14_p082_f150_A_sin_1.fits
    with:
    * filever: the version of the file
    * w14: the number of the wafer (here 14)
    * p082: the pixel number (here 082)
    * f150: the frequency band (here 150 GHz)
    * A: the polarization detector number (here A)
    * sin_1: the spin dependence and component written, here the $h_n$ component with spin 1 
    
    Only the latest part of the file actually matters, considering the $sin$ or $cos$ component of the $h_n$ map as well as its spin dependence. 

    Parameters
    ----------
    name_file: str
        The version of the file, given so that `hp.read_map(name_file + '_sin_1.fits')` can be used to read the file (with `sin_1` being the sin or cos component of the $h_n$ maps and the spin dependence)
    list_spin (list[int]): 
        List of the spin to read
    list_prefix: list[str]
        List of the prefixes to read, typically ['A_', 'B_'] for two polarization detectors in a pair
    list_weights: list[float], optional
        List of the weights per detector, to apply to the $h_n$ so that the total $h_n$ maps are weighted by the total nhits of the detectors, if None, the nhits is assumed to be the same for all detectors and a weight of 1 is applied, except if new_weighting_bool is True, in which case the weights are computed from the number of pixels with non-zero $h_n$ values.
    mask: np.ndarray, optional
        HEALPix mask to define the area of the sky to compute the $h_n$ maps. If None, the full maps are read.
    format_file: str
        Format of the file to read, must be 'fits', 'npy' or 'npz', otherwise a ValueError is raised
    new_weighting_bool: bool, optional
        If True, the weights are computed from the number of pixels with non-zero $h_n$ values, so that the total $h_n$ maps are weighted by the number of detectors observing each pixel. 

    Returns
    -------
    h_n: Spin_maps
        The $h_n$ maps stored in a dictionary of spins and ordered as [n_det, n_pix], with n_det=1, except for spin=0 which dimension is [1,1] and only contains the float 1.

    Note:
    """
    try:
        from tqdm import tqdm
    except ImportError:
        raise ImportError('tqdm is not installed. Please install it with "pip install tqdm"')

    assert np.unique(list_spin).size == np.array(list_spin).size, 'The list of spins must be unique'
    assert (np.array(list_spin) >= 0).all(), 'The spins provided must be positive, their negative counterpart will be computed from the components read'

    assert format_file in ['npy', 'npz', 'h5', 'hdf5', 'H5', 'hdf', 'fits'], "Format file must be 'fits', 'npy', 'h5', 'hdf5', 'H5', 'hdf' or 'npz' for TOAST h maps"

    if single_precision:
        dtype = np.complex64
        error_precision = 1e-8
    else:
        dtype = np.complex128
        error_precision = 1e-15


    if duplicate_maps_with_prefix:
        print("Duplicate maps with prefix is enabled", flush=True)

    number_detectors_prefix = len(list_prefix)
    n_det = len(list_name_files) * number_detectors_prefix

    if list_weights is None:
        list_weights = np.ones(n_det, dtype=float) / n_det
    else:
        list_weights = np.asarray(list_weights, dtype=float)
        assert list_weights.shape[0] == n_det and list_weights.ndim <= 2, "list_weights must be a 1D array of size n_det or a 2D array of shape (n_det, n_pix)"
    
    if mask is None:
        boolean_mask = ...
        fake_h_n_map = read_file(
                    list_name_files[0]+'_{}_sin_{}'.format(list_prefix[0].replace('_',''),list_spin[0]), 
                    format_file=format_file,
                    boolean_mask=boolean_mask,
                    projection_pixel=projection_pixel,
                )
        n_pix = np.prod(fake_h_n_map[boolean_mask].shape)
    elif mask is not None:
        boolean_mask = np.bool_(mask)
        n_pix = boolean_mask[boolean_mask].size

    total_list_spin = list_spin + [-spin for spin in list_spin]
    if 0 in total_list_spin and total_list_spin.count(0) > 1:
        total_list_spin.remove(0)  

    h_n_dictionary = Spin_maps.from_dictionary(
            {spin: np.zeros((n_det, n_pix), dtype=dtype) for spin in total_list_spin}
        ) # Initialize dictionary for spins

    for j, name_file in enumerate(tqdm(list_name_files)):
        spin_h_n = dict()
        if not duplicate_maps_with_prefix:
            for prefix in list_prefix:
                for spin in list_spin:
                    spin_h_n[prefix+'sin_{}'.format(spin)] = read_file(
                        name_file+'_{}_sin_{}'.format(prefix.replace('_',''),spin), 
                        format_file=format_file,
                        boolean_mask=boolean_mask,
                        projection_pixel=projection_pixel,
                    )
                    spin_h_n[prefix+'cos_{}'.format(spin)] = read_file(
                        name_file+'_{}_cos_{}'.format(prefix.replace('_',''),spin), 
                        format_file=format_file,
                        boolean_mask=boolean_mask,
                        projection_pixel=projection_pixel,
                    )
        else:
            for spin in list_spin:
                spin_h_n[list_prefix[0]+'sin_{}'.format(spin)] = read_file(
                    name_file+'_{}_sin_{}'.format(list_prefix[0].replace('_',''),spin), 
                    format_file=format_file,
                    boolean_mask=boolean_mask,
                    projection_pixel=projection_pixel,
                )
                spin_h_n[list_prefix[0]+'cos_{}'.format(spin)] = read_file(
                    name_file+'_{}_cos_{}'.format(list_prefix[0].replace('_',''),spin), 
                    format_file=format_file,
                    boolean_mask=boolean_mask,
                    projection_pixel=projection_pixel,
                )
            for prefix in list_prefix[1:]:
                for spin in list_spin:
                    spin_h_n[prefix+'sin_{}'.format(spin)] = spin_h_n[list_prefix[0]+'sin_{}'.format(spin)]
                    spin_h_n[prefix+'cos_{}'.format(spin)] = spin_h_n[list_prefix[0]+'cos_{}'.format(spin)]

        for spin in list_spin:
            for count_prefix, prefix in enumerate(list_prefix):
                sin_spin_h_n = spin_h_n[prefix+'sin_{}'.format(spin)]
                cos_spin_h_n = spin_h_n[prefix+'cos_{}'.format(spin)]

                h_n_dictionary[spin][j*number_detectors_prefix + count_prefix,...].real = cos_spin_h_n * list_weights[j]
                h_n_dictionary[spin][j*number_detectors_prefix + count_prefix,...].imag = sin_spin_h_n * list_weights[j]
        spin_h_n = None
    
    for spin in list_spin:
        h_n_dictionary[-spin] = np.conj(h_n_dictionary[spin])


    print("Finalizing h_n dictionary...", flush=True)

    h_n_dictionary = reweight_h_maps(
        h_dictionary=h_n_dictionary,
        list_weights=list_weights,
        new_weighting_bool=new_weighting_bool,
        error_precision=error_precision,
        list_spin=list_spin,
    )

    return h_n_dictionary

def read_lbs_h_maps(
        list_detector_names: list[str], 
        prefix: str='h_maps_det_',
        list_spin: list[int]=[np.array([2,0]),np.array([4,0])], 
        list_weights=None, 
        mask: np.ndarray=None, 
        format_file: str='h5',
        new_weighting_bool: bool=False,
        single_precision: bool=False,
        # projection_pixel: str='healpix',
    ):
    """
    Read the $h_{n,m}$ map as generated by litebird_sim, 
    which filename is preferrentially given as
        h_maps_det_*.h5
    with:
        * the wafer number, detector id, frequency band, etc.

    Parameters
    ----------
    name_file: str
        The version of the file, given so that `hp.read_map(name_file + '_sin_1.fits')` can be used to read the file (with `sin_1` being the sin or cos component of the $h_{n,m}$ maps and the spin dependence)
    list_spin: list[int]=[(2,0),(4,0)], 
        List of spins to read
    list_prefix: list[str]
        List of the prefixes to read, typically ['A_', 'B_'] for two polarization detectors in a pair
    list_weights: list[float], optional
        List of the weights per detector, to apply to the $h_{n,m}$ so that the total $h_{n,m}$ maps are weighted by the total nhits of the detectors, if None, the nhits is assumed to be the same for all detectors and a weight of 1 is applied, except if new_weighting_bool is True, in which case the weights are computed from the number of pixels with non-zero $h_{n,m}$ values.
    mask: np.ndarray, optional
        HEALPix mask to define the area of the sky to compute the $h_{n,m}$ maps. If None, the full maps are read.
    format_file: str
        Format of the file to read, must be 'h5', 'hdf5', 'H5' or 'hdf', otherwise a ValueError is raised, as other formats are not supported for litebird_sim h maps
    new_weighting_bool: bool, optional
        If True, the weights are computed from the number of pixels with non-zero $h_n$ values, so that the total $h_n$ maps are weighted by the number of detectors observing each pixel. 

    Returns
    -------
    h_n: Spin_maps
        The $h_n$ maps stored in a dictionary of spins and ordered as [n_det, n_pix], with n_det=1, except for spin=0 which dimension is [1,1] and only contains the float 1.

    Note:
    """
    try:
        from tqdm import tqdm
    except ImportError:
        raise ImportError('tqdm is not installed. Please install it with "pip install tqdm"')

    list_spin = [Spin_nm(spin) for spin in list_spin]

    assert np.unique(np.atleast_2d(list_spin).sum(axis=1)).size == np.array(list_spin).shape[0], 'The list of spins must be unique'
    assert (np.atleast_2d(list_spin)[0] >= 0).all(), 'The pointing spins provided must be positive, their negative counterpart will be computed from the components read'
    assert np.array(list_spin).ndim == 1 or (np.array(list_spin).ndim == 2 and np.array(list_spin).shape[1] == 2), 'The list of spins must be a 1D array of (pointing) spins or a 2D array of shape (n_spins, 2) for (n,m) spins'
    assert format_file in ['h5', 'hdf5', 'H5', 'hdf'], "Format file must be 'h5', 'hdf5', 'H5' or 'hdf' for litebird_sim h maps"

    

    projection_pixel='healpix' # Currently only healpix is supported for lbs h maps

    if single_precision:
        dtype = np.complex64
        error_precision = 1e-8
    else:
        dtype = np.complex128
        error_precision = 1e-15

    n_det = len(list_detector_names)

    if list_weights is None:
        list_weights = np.ones(n_det, dtype=float) / n_det
    else:
        list_weights = np.asarray(list_weights, dtype=float)
        assert list_weights.shape[0] == n_det and list_weights.ndim <= 2, "list_weights must be a 1D array of size n_det or a 2D array of shape (n_det, n_pix)"
    
    if mask is None:
        boolean_mask = ...
        fake_h_n_map = read_file(
                    prefix+list_detector_names[0], 
                    format_file=format_file,
                    projection_pixel=projection_pixel,
                )['{},{}'.format(0,0)]['Re'].ravel()
        n_pix = np.prod(fake_h_n_map.shape)
    elif mask is not None:
        boolean_mask = np.bool_(mask)
        n_pix = boolean_mask[boolean_mask].size

    total_list_spin = list_spin + [-spin for spin in list_spin if np.sum(spin) != 0]
    # if 0 in total_list_spin and total_list_spin.count(0) > 1:
    #     total_list_spin.remove(0)  

    h_n_dictionary = Spin_maps.from_dictionary(
            {spin: np.zeros((n_det, n_pix), dtype=dtype) for spin in total_list_spin}
        ) # Initialize dictionary for spins

    for j, name_file in enumerate(tqdm(list_detector_names)):

        h_map_file = read_file(
            name_file=name_file, 
            format_file=format_file,
            boolean_mask=boolean_mask,
            projection_pixel=projection_pixel,
        )
        for spin in list_spin:
            real_part = h_map_file['{},{}'.format(*spin)]["Re"][boolean_mask]
            imag_part = h_map_file['{},{}'.format(*spin)]["Im"][boolean_mask]
            h_n_dictionary[spin][j,...].real = np.where(
                real_part != hp.UNSEEN, 
                real_part, 
                0.0
            ) * list_weights[j]
            h_n_dictionary[spin][j,...].imag = np.where(
                imag_part != hp.UNSEEN,
                imag_part, 
                0.0
            ) * list_weights[j]
        h_map_file.close()
    
    for spin in list_spin:
        h_n_dictionary[-spin] = np.conj(h_n_dictionary[spin])


    print("Finalizing h_n dictionary...", flush=True)

    h_n_dictionary = reweight_h_maps(
        h_dictionary=h_n_dictionary,
        list_weights=list_weights,
        new_weighting_bool=new_weighting_bool,
        error_precision=error_precision,
        list_spin=list_spin,
    )

    all_spins = np.array(h_n_dictionary.spins)
    if (all_spins[:,1] == 0).all():
        print("No HWP angle spins, removing m=0 spins from the h_nm dictionary...", flush=True)
        h_n_dictionary = Spin_maps.from_dictionary(
            {spin[0]: h_n_dictionary[spin] for spin in h_n_dictionary.spins}
        )
    return h_n_dictionary

def build_mask_from_toast_h_maps(
        list_name_files: list[str], 
        list_prefix: list[str]=['A_', 'B_'], 
        format_file: str='npz',
        spin_to_read: int=1,
        return_detectors_hits: bool=False,
        projection_pixel: str='healpix',
    ):
    """
    Read the $h_n$ map as generated by TOAST, 
    which filename is preferrentially given as
        filever_w14_p082_f150_A_sin_1.fits
    with:
    * filever: the version of the file
    * w14: the number of the wafer (here 14)
    * p082: the pixel number (here 082)
    * f150: the frequency band (here 150 GHz)
    * A: the polarization detector number (here A)
    * sin_1: the spin dependence and component written, here the $h_n$ component with spin 1 
    
    Only the latest part of the file actually matters, considering the $sin$ or $cos$ component of the $h_n$ map as well as its spin dependence. 

    Parameters
    ----------
    name_file: str
        The version of the file, given so that `hp.read_map(name_file + '_sin_1.fits')` can be used to read the file (with `sin_1` being the sin or cos component of the $h_n$ maps and the spin dependence)
    list_spin (list[int]): 
        List of the spin to read
    list_prefix: list[str]
        List of the prefixes to read, typically ['A_', 'B_'] for two polarization detectors in a pair
    format_file: str
        Format of the file to read, must be 'fits', 'npy' or 'npz', otherwise a ValueError is raised


    Returns
    -------
    h_n: Spin_maps
        The $h_n$ maps stored in a dictionary of spins and ordered as [n_det, n_pix], with n_det=1, except for spin=0 which dimension is [1,1] and only contains the float 1.

    Note:
    """
    try:
        from tqdm import tqdm
    except ImportError:
        raise ImportError('tqdm is not installed. Please install it with "pip install tqdm"')

    assert format_file in ['npy', 'npz'] or format_file in ['h5', 'hdf5', 'H5', 'hdf'] or format_file == 'fits'

    mask = np.zeros_like(
        read_file(
            list_name_files[0]+'_{}_sin_{}'.format(list_prefix[0].replace('_',''),spin_to_read), format_file=format_file,
            projection_pixel=projection_pixel,), 
        dtype=np.float64).ravel()
    mask_detectors = np.int64(np.bool_(mask))

    
    for name_file in tqdm(list_name_files):
        for prefix in list_prefix:
            map_cos_sin = np.abs(read_file(
                name_file+'_{}_sin_{}'.format(prefix.replace('_',''),spin_to_read), 
                format_file=format_file,
                projection_pixel=projection_pixel,
            )[:]).ravel() + np.abs(read_file(
                name_file+'_{}_cos_{}'.format(prefix.replace('_',''),spin_to_read), 
                format_file=format_file,
                projection_pixel=projection_pixel,
            )[:]).ravel()
            mask += map_cos_sin
            mask_detectors += np.int64(np.bool_(map_cos_sin))

    if format_file in ['h5', 'hdf5', 'H5', 'hdf'] and projection_pixel == 'healpix':
        reorder_output = lambda x: hp.reorder(x, n2r=True)
    else:
        reorder_output = lambda x: x

    if return_detectors_hits:
        return reorder_output(np.int8(np.bool_(mask))), reorder_output(mask_detectors)
    return reorder_output(np.int8(np.bool_(mask)))

def build_mask_from_lbs_h_maps(
        list_name_files: list[str], 
        format_file: str='h5',
        spin_to_read: int|tuple=(0,0),
        return_detectors_hits: bool=False,
        projection_pixel: str='healpix',
    ):
    """
    Read the $h_n$ map as generated by TOAST, 
    which filename is preferrentially given as
        *.h5
        TODO: to replace
    with:
    * filever: the version of the file
    * w14: the number of the wafer (here 14)
    * p082: the pixel number (here 082)
    * f150: the frequency band (here 150 GHz)
    * A: the polarization detector number (here A)
    * sin_1: the spin dependence and component written, here the $h_n$ component with spin 1 
    
    Only the latest part of the file actually matters, considering the $sin$ or $cos$ component of the $h_n$ map as well as its spin dependence. 

    Parameters
    ----------
    name_file: str
        The version of the file, given so that `hp.read_map(name_file + '_sin_1.fits')` can be used to read the file (with `sin_1` being the sin or cos component of the $h_n$ maps and the spin dependence)
    list_spin (list[int]): 
        List of the spin to read
    list_prefix: list[str]
        List of the prefixes to read, typically ['A_', 'B_'] for two polarization detectors in a pair
    format_file: str
        Format of the file to read, must be 'fits', 'npy' or 'npz', otherwise a ValueError is raised


    Returns
    -------
    h_n: Spin_maps
        The $h_n$ maps stored in a dictionary of spins and ordered as [n_det, n_pix], with n_det=1, except for spin=0 which dimension is [1,1] and only contains the float 1.

    Note:
    """
    try:
        from tqdm import tqdm
    except ImportError:
        raise ImportError('tqdm is not installed. Please install it with "pip install tqdm"')

    assert format_file in ['h5', 'hdf5', 'H5', 'hdf'], "Format file must be 'h5', 'hdf5', 'H5' or 'hdf' for litebird_sim h maps"

    mask = np.zeros_like(
        read_file(
            list_name_files[0], 
            format_file=format_file,
            projection_pixel=projection_pixel
        )['{},{}'.format(*spin_to_read)]["Re"][:].ravel(), 
        dtype=np.float64).ravel()
    mask_detectors = np.int64(np.bool_(mask))

    
    for name_file in tqdm(list_name_files):
        h_map_file = read_file(
            name_file=name_file, 
            format_file=format_file,
            projection_pixel=projection_pixel,
        )['{},{}'.format(*spin_to_read)]["Re"][:].ravel()
        
        mask_contribution = np.where(
            h_map_file>0,
            np.ones_like(h_map_file),
            0
        )
        mask += mask_contribution
        mask_detectors += np.int64(np.bool_(mask_contribution))

    if return_detectors_hits:
        return np.int8(np.bool_(mask)), mask_detectors
    return np.int8(np.bool_(mask))

def read_ellipticity_values_from_yaml_file(
        path_values_ellipticity: str,
        transform_into_dict: bool=False,
        detector_features_all: list[str]=None,
    ):
    if transform_into_dict:
        assert detector_features_all is not None, "detector_features_all must be provided if transform_into_array is True"

    with open(path_values_ellipticity) as file:
        ellipticity_file = yaml.safe_load(file)
    
    if transform_into_dict:
        ellipticity_parameters_dict = {
            key: 
            np.array(
                [ellipticity_file[det_name][key] for det_name in detector_features_all]
            )
            for key in ellipticity_file[
                list(ellipticity_file.keys())[-1]
            ].keys()
        }
        ellipticity_parameters_dict['ellipticity_parameter_convention'] = ellipticity_file['ellipticity_parameter_convention']
        return ellipticity_parameters_dict
    return ellipticity_file


def read_values_from_yaml_file(
        path_yaml: str,
        transform_into_dict: bool=False,
        detector_features_all: list[str]=None,
        retrieve_all_parameters: bool=False,
        list_additional_parameters_to_retrieve: list[str]=None,
    ):
    if transform_into_dict:
        assert detector_features_all is not None, "detector_features_all must be provided if transform_into_array is True"

    with open(path_yaml) as file:
        dictionary_yaml = yaml.safe_load(file)

    if not transform_into_dict:
        return dictionary_yaml
    
    else:
        list_keys_parameter_values = dictionary_yaml[detector_features_all[0]].keys()
        output_parameters_dict = {
            key: 
            np.array(
                [dictionary_yaml[det_name][key] for det_name in detector_features_all]
            )
            for key in list_keys_parameter_values
        }

        if retrieve_all_parameters:
            other_parameters = list(dictionary_yaml.keys())
            other_parameters.remove(detector_features_all)

            for key in other_parameters:
                output_parameters_dict[key] = dictionary_yaml[key]
        if list_additional_parameters_to_retrieve is not None:
            for key in list_additional_parameters_to_retrieve:
                if key in dictionary_yaml:
                    output_parameters_dict[key] = dictionary_yaml[key]
        return output_parameters_dict



def read_spherical_derivatives_from_file(
        path_spherical_derivatives,
        is_car: bool=False,
    ):

    wcs_car = None

    if os.path.isfile(path_spherical_derivatives):
        if not is_car:
            spherical_derivatives_array = hp.read_map(
                path_spherical_derivatives, 
                field=None
            )
        else:
            spherical_derivatives_array = flatten_CAR_maps(
                enmap.read_map(
                    path_spherical_derivatives
                )
            )
            wcs_car = spherical_derivatives_array.wcs
        assert spherical_derivatives_array.shape[0] == (6), "The spherical derivatives file must contain 6 maps with shape (6, npix)."

        list_derivatives = ['theta', 'phi', 'theta_theta', 'theta_phi', 'phi_phi']

        get_final_map = lambda x: x if wcs_car is None else enmap.ndmap(
            x, 
            wcs=wcs_car
        )

        return {
            derivative: get_final_map(spherical_derivatives_array[i+1]) 
            for i, derivative in enumerate(list_derivatives)
        }
