# This file is part of SMARTIES.
# Copyright (C) 2024 CNRS / SciPol developers
#
# SMARTIES is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SMARTIES is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SMARTIES. If not, see <https://www.gnu.org/licenses/>.

import numpy as np
import healpy as hp
from opt_einsum import contract
import h5py
from smarties.hn import Spin_maps

def read_file(
        name_file:str, 
        format_file:str='fits', 
        boolean_mask:np.ndarray=None,
        reorder: bool=False,
        dtype=np.float64,
    ):
    """
    Read the $h_n$ maps as provided either in FITS, NPY or NPZ
    format, and eventually mask them. 

    Parameters
    ----------
    name_file: str
        Path to the $h_n$ file to be read. If the path provided does
        not contain the fomat suffix, in '.fits', '.npy' or '.npz',
        the suffix corresponding to the format indicated in format_file
        will be concatenated. 
    format_file: str
        String indicated the format of the file to be read, must be 
        either 'fits', 'npy' or 'npz' otherwise a ValueError is raised 
    boolean_mask: array[bool] | Ellipsis
        Optional, boolean array corresponding to the selected pixels in 
        the array to retain after loading the file. By default, return 
        all pixels. Note that this option is not active for 'npz' format
        files. If None, the full maps are read.

    Returns
    -------
        Array containing the $h_n$ map read, from which only the relevant
        pixels are possibly retained. 
    """
    if boolean_mask is None:
        boolean_mask = ...
    # else:
    #     boolean_mask = mask != 0

    if format_file == 'fits':
        if not name_file.endswith('.fits'):
            name_file = name_file + '.fits'
        return hp.read_map(name_file)[boolean_mask]
    elif format_file == 'npy':
        if not name_file.endswith('.npy'):
            name_file = name_file + '.npy'
        # return np.load(name_file)[boolean_mask]
        return np.memmap(name_file, mode='r', dtype=dtype)[boolean_mask]
    elif format_file == 'npz':
        if not name_file.endswith('.npz'):
            name_file = name_file + '.npz'
        return np.load(name_file) #, allow_pickle=True)
    elif format_file in ['h5', 'hdf5', 'H5', 'hdf']:
        if reorder:
            reorder_function = lambda x: hp.reorder(x, n2r=True)
        else:
            reorder_function = lambda x: x
        return reorder_function(h5py.File(name_file+'.hdf5', "r")['map'][0])
    else:
        raise ValueError("Unknown format: {}".format(format_file))


def read_detectors_h_n_file_dictionary(
        list_name_files: list[str], 
        list_spin: list[int]=[2,4], 
        list_prefix: list[str]=['A_', 'B_'], 
        list_weights=None, 
        mask: np.ndarray=None, 
        format_file: str='npz',
        new_weighting_bool: bool=False,
        single_precision: bool=False,
    ):
    """
    Read the $h_n$ map as generated by TOAST, 
    which filename is preferrentially given as
        filever_w14_p082_f150_A_sin_1.fits
    with:
    * filever: the version of the file
    * w14: the number of the wafer (here 14)
    * p082: the pixel number (here 082)
    * f150: the frequency band (here 150 GHz)
    * A: the polarization detector number (here A)
    * sin_1: the spin dependence and component written, here the $h_n$ component with spin 1 
    
    Only the latest part of the file actually matters, considering the $sin$ or $cos$ component of the $h_n$ map as well as its spin dependence. 

    Parameters
    ----------
    name_file: str
        The version of the file, given so that `hp.read_map(name_file + '_sin_1.fits')` can be used to read the file (with `sin_1` being the sin or cos component of the $h_n$ maps and the spin dependence)
    list_spin (list[int]): 
        List of the spin to read
    list_prefix: list[str]
        List of the prefixes to read, typically ['A_', 'B_'] for two polarization detectors in a pair
    list_weights: list[float], optional
        List of the weights per detector, to apply to the $h_n$ so that the total $h_n$ maps are weighted by the total nhits of the detectors, if None, the nhits is assumed to be the same for all detectors and a weight of 1 is applied, except if new_weighting_bool is True, in which case the weights are computed from the number of pixels with non-zero $h_n$ values.
    mask: np.ndarray, optional
        HEALPix mask to define the area of the sky to compute the $h_n$ maps. If None, the full maps are read.
    format_file: str
        Format of the file to read, must be 'fits', 'npy' or 'npz', otherwise a ValueError is raised
    new_weighting_bool: bool, optional
        If True, the weights are computed from the number of pixels with non-zero $h_n$ values, so that the total $h_n$ maps are weighted by the number of detectors observing each pixel. 

    Returns
    -------
    h_n: Spin_maps
        The $h_n$ maps stored in a dictionary of spins and ordered as [n_det, n_pix], with n_det=1, except for spin=0 which dimension is [1,1] and only contains the float 1.

    Note:
    """
    try:
        from tqdm import tqdm
    except ImportError:
        raise ImportError('tqdm is not installed. Please install it with "pip install tqdm"')

    assert np.unique(list_spin).size == np.array(list_spin).size, 'The list of spins must be unique'
    assert (np.array(list_spin) >= 0).all(), 'The spins provided must be positive, their negative counterpart will be computed from the components read'

    assert format_file in ['npy', 'npz'] or format_file in ['h5', 'hdf5', 'H5', 'hdf'] or format_file == 'fits'

    if single_precision:
        dtype = np.complex64
    else:
        dtype = np.complex128

    if dtype == np.complex64:
        error_precision = 1e-8
    elif dtype == np.complex128:
        error_precision = 1e-15
    else:
        raise ValueError('dtype must be np.complex64 or np.complex128')

    number_detectors_prefix = len(list_prefix)
    n_det = len(list_name_files) * number_detectors_prefix

    if list_weights is None:
        list_weights = np.ones(n_det, dtype=float) / n_det
    else:
        list_weights = np.asarray(list_weights, dtype=float)
        assert list_weights.shape[0] == n_det and list_weights.ndim <= 2, "list_weights must be a 1D array of size n_det or a 2D array of shape (n_det, n_pix)"
    
    if mask is None:
        boolean_mask = ...
    elif mask is not None:
        boolean_mask = np.bool(mask)

    total_list_spin = list_spin + [-spin for spin in list_spin]
    if 0 in total_list_spin and total_list_spin.count(0) > 1:
        total_list_spin.remove(0)

    n_pix = boolean_mask[boolean_mask].size

    h_n_dictionary = Spin_maps.from_dictionary(
            {spin: np.zeros((n_det, n_pix), dtype=dtype) for spin in total_list_spin}
        ) # Initialize dictionary for spins

    for j, name_file in enumerate(tqdm(list_name_files)):
        # if format_file != 'fits':
        #     spin_h_n = read_file(name_file, format_file=format_file)
        # else:
        spin_h_n = dict()

        for prefix in list_prefix:
            for spin in list_spin:
                spin_h_n[prefix+'sin_{}'.format(spin)] = read_file(
                    name_file+'_{}_sin_{}'.format(prefix.replace('_',''),spin), 
                    format_file=format_file,
                    boolean_mask=boolean_mask,
                )
                spin_h_n[prefix+'cos_{}'.format(spin)] = read_file(
                    name_file+'_{}_cos_{}'.format(prefix.replace('_',''),spin), 
                    format_file=format_file,
                    boolean_mask=boolean_mask,
                )

        for spin in list_spin:
            for count_prefix, prefix in enumerate(list_prefix):
                sin_spin_h_n = spin_h_n[prefix+'sin_{}'.format(spin)]
                cos_spin_h_n = spin_h_n[prefix+'cos_{}'.format(spin)]
                # h_n_dictionary[spin].append((cos_spin_h_n + 1j * sin_spin_h_n)[np.newaxis,...] * list_weights[j])
                # h_n_dictionary[-spin].append((cos_spin_h_n - 1j * sin_spin_h_n)[np.newaxis,...] * list_weights[j])
                
                # h_n_dictionary[spin][j*number_detectors_prefix + count_prefix,...] = (cos_spin_h_n + 1j * sin_spin_h_n) * list_weights[j]
                h_n_dictionary[spin][j*number_detectors_prefix + count_prefix,...].real = cos_spin_h_n * list_weights[j]
                h_n_dictionary[spin][j*number_detectors_prefix + count_prefix,...].imag = sin_spin_h_n * list_weights[j]
        spin_h_n = None
    
    for spin in list_spin:
        h_n_dictionary[-spin] = np.conj(h_n_dictionary[spin])


    print("Finalizing h_n dictionary...", flush=True)
    # for spin in total_list_spin:
    #     h_n_dictionary[spin] = np.vstack(h_n_dictionary[spin])

    

    if 0 not in h_n_dictionary.spins:
        h_n_dictionary[0] = list_weights[..., np.newaxis] if list_weights.ndim == 1 else list_weights
        if new_weighting_bool:
            print("Applying new weighting to h_n dictionary...", flush=True)
            # new_weighting_array = np.zeros(h_n_dictionary[list_spin[0]].shape, dtype=bool)
            # pixel_map_weighting_array = np.zeros(n_pix, dtype=int)

            # for spin in [list_spin[0], -list_spin[0]]:
            # new_weighting_array = np.logical_or(new_weighting_array, np.abs(h_n_dictionary[spin]) > 1e-14)
            array_hits_detector_pixel = np.int64(np.logical_or(
                np.abs(h_n_dictionary[list_spin[0]]) > 10*error_precision,
                np.abs((h_n_dictionary[-list_spin[0]]) > 10*error_precision)
                )
            )
            pixel_map_weighting_array = (array_hits_detector_pixel).sum(axis=0)
            # pixel_map_weighting_array = np.sum(new_weighting_array, axis=0)

            if 0 in pixel_map_weighting_array:
                print("Warning: some pixels are not observed by any detector, they will have their h_n values set to zero", flush=True)
                print("Number of unobserved pixels: {}".format(np.sum(pixel_map_weighting_array==0)), flush=True)
                print("Total number of pixels: {}".format(pixel_map_weighting_array.size), flush=True)
                print("Fraction of unobserved pixels: {:.2e}".format(np.sum(pixel_map_weighting_array==0)/pixel_map_weighting_array.size), flush=True)
            
            for spin in total_list_spin:
                if spin != 0:
                    h_n_dictionary[spin][...,pixel_map_weighting_array!=0] = contract(
                        'd...,d...,...->d...',
                        h_n_dictionary[spin], 
                        list_weights,
                        1 / pixel_map_weighting_array[pixel_map_weighting_array!=0]
                    )
                
            h_n_dictionary[0] = np.where(array_hits_detector_pixel==0, 0, array_hits_detector_pixel / pixel_map_weighting_array )
    else:
        print("Warning: spin 0 already present in h_n dictionary, re-weighting applied.", flush=True)
        cond_non_zero = h_n_dictionary[0] != 0
        print(h_n_dictionary[0].shape, flush=True)
        inverse_weights = 1 / list_weights[...,None] if list_weights.ndim == 1 else np.where(cond_non_zero, 1 / list_weights[...,cond_non_zero], 0)
        
        sum_hits = h_n_dictionary[0].sum(axis=0)

        for spin in total_list_spin:
                if spin != 0:

                    h_n_dictionary[spin][cond_non_zero] *= (inverse_weights * h_n_dictionary[0] / sum_hits)[cond_non_zero]
                    
        
        h_n_dictionary[0] = np.where(cond_non_zero, h_n_dictionary[0] / sum_hits, 0)
    # h_n_spin_dict = h_n_dictionary)
    return h_n_dictionary


def build_mask_from_h_n_maps(
        list_name_files: list[str], 
        list_prefix: list[str]=['A_', 'B_'], 
        format_file: str='npz',
        spin_to_read: int=1,
        return_detectors_hits: bool=False,
    ):
    """
    Read the $h_n$ map as generated by TOAST, 
    which filename is preferrentially given as
        filever_w14_p082_f150_A_sin_1.fits
    with:
    * filever: the version of the file
    * w14: the number of the wafer (here 14)
    * p082: the pixel number (here 082)
    * f150: the frequency band (here 150 GHz)
    * A: the polarization detector number (here A)
    * sin_1: the spin dependence and component written, here the $h_n$ component with spin 1 
    
    Only the latest part of the file actually matters, considering the $sin$ or $cos$ component of the $h_n$ map as well as its spin dependence. 

    Parameters
    ----------
    name_file: str
        The version of the file, given so that `hp.read_map(name_file + '_sin_1.fits')` can be used to read the file (with `sin_1` being the sin or cos component of the $h_n$ maps and the spin dependence)
    list_spin (list[int]): 
        List of the spin to read
    list_prefix: list[str]
        List of the prefixes to read, typically ['A_', 'B_'] for two polarization detectors in a pair
    list_weights: list[float], optional
        List of the weights per detector, to apply to the $h_n$ so that the total $h_n$ maps are weighted by the total nhits of the detectors, if None, the nhits is assumed to be the same for all detectors and a weight of 1 is applied, except if new_weighting_bool is True, in which case the weights are computed from the number of pixels with non-zero $h_n$ values.
    mask: np.ndarray, optional
        HEALPix mask to define the area of the sky to compute the $h_n$ maps. If None, the full maps are read.
    format_file: str
        Format of the file to read, must be 'fits', 'npy' or 'npz', otherwise a ValueError is raised
    new_weighting_bool: bool, optional
        If True, the weights are computed from the number of pixels with non-zero $h_n$ values, so that the total $h_n$ maps are weighted by the number of detectors observing each pixel. 

    Returns
    -------
    h_n: Spin_maps
        The $h_n$ maps stored in a dictionary of spins and ordered as [n_det, n_pix], with n_det=1, except for spin=0 which dimension is [1,1] and only contains the float 1.

    Note:
    """
    try:
        from tqdm import tqdm
    except ImportError:
        raise ImportError('tqdm is not installed. Please install it with "pip install tqdm"')

    assert format_file in ['npy', 'npz'] or format_file in ['h5', 'hdf5', 'H5', 'hdf'] or format_file == 'fits'

    mask = np.zeros_like(
        read_file(
            list_name_files[0]+'_{}_sin_{}'.format(list_prefix[0].replace('_',''),spin_to_read), format_file=format_file), 
        dtype=np.float64).ravel()
    mask_detectors = np.int64(np.bool(mask))

    
    for name_file in tqdm(list_name_files):
        for prefix in list_prefix:
            map_cos_sin = np.abs(read_file(
                name_file+'_{}_sin_{}'.format(prefix.replace('_',''),spin_to_read), 
                format_file=format_file
            )[:]) + np.abs(read_file(
                name_file+'_{}_cos_{}'.format(prefix.replace('_',''),spin_to_read), 
                format_file=format_file
            )[:])
            mask += map_cos_sin
            mask_detectors += np.int64(np.bool(map_cos_sin))
            # print(name_file, np.int8(np.bool(map_cos_sin))[np.int8(np.bool(map_cos_sin))<0])

    if format_file in ['h5', 'hdf5', 'H5', 'hdf']:
        reorder_output = lambda x: hp.reorder(x, n2r=True)
    else:
        reorder_output = lambda x: x

    if return_detectors_hits:
        return reorder_output(np.int8(np.bool(mask))), reorder_output(mask_detectors)
    return reorder_output(np.int8(np.bool(mask)))
