import numpy as np
import healpy as hp


def read_h_n_files(name_file, list_spin=[2,4]):
    """
    Read the $h_n$ map as generated by TOAST, 
    which filename is preferrentially given as
        filever_w14_p082_f150_A_sin_1.fits
    with:
    * filever: the version of the file
    * w14: the number of the wafer (here 14)
    * p082: the pixel number (here 082)
    * f150: the frequency band (here 150 GHz)
    * A: the polarization detector number (here A)
    * sin_1: the spin dependence and component written, here the $h_n$ component with spin 1 
    
    Only the latest part of the file actually matters, considering the $sin$ or $cos$ component of the $h_n$ map as well as its spin dependence. 

    Args:
        name_file (str): the version of the file, given so that `hp.read_map(name_file + '_sin_1.fits')` can be used to read the file (with `sin_1` being the sin or cos component of the $h_n$ maps and the spin dependence)
        list_spin (list[int]): list of the spin to read

    Returns:
        h_n (np.ndarray): the $h_n$ maps ordered as [2*n_spin, n_pix] with n_spin being the length of list_spin and storing the spins strictly increasing (eg. [-4, -2, 2, 4] if list_spin=[2,4]), the maps for spin=0 (full of ones) not included 

    Note:
    """
    assert np.unique(list_spin) == np.array(list_spin), 'The list of spins must be unique'
    assert (np.array(list_spin) > 0).all(), 'The spins provided must be positive, their negative counterpart will be computed from the components read'

    h_n_spin_dict = dict()
    
    for i,spin in enumerate(list_spin):
        sin_spin_h_n = hp.read_map(name_file + '_sin_{}.fits'.format(spin))
        cos_spin_h_n = hp.read_map(name_file + '_cos_{}.fits'.format(spin))
        h_n_spin_dict[spin] = cos_spin_h_n + 1j * sin_spin_h_n
        h_n_spin_dict[-spin] = cos_spin_h_n - 1j * sin_spin_h_n

    return h_n_spin_dict
